config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  namespace :user do
    resources :event
    resources :friendship
    resources :category, only: [:show, :index, :destroy, :edit, :update]
  end
  authenticated :user do
    root to: 'user/event#new', as: :authenticated_root
  end
  get "/user/calendar/month", to: "user/calendar#month"
  get "/user/calendar/week", to: "user/calendar#week"
  get "/user/calendar/day", to: "user/calendar#day"
  post "/user/event/unshare", to: "user/event#unshare"
  post "/user/friendship/create", to: "user/friendship#create"
  devise_scope :user do
    root to: "user/event#new"
  end
  get "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_users
  has_many :users, through: :event_users
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :event_categories
  has_many :categories, through: :event_categories
  accepts_nested_attributes_for :categories, reject_if: proc { |attributes| attributes['name'].blank? }
  validates :short_description, presence: true, length: {maximum: 140}
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :additional_info, length: {maximum: 280}


  def categories_attributes=(category_attributes)
    if category_attributes[:name] != ""
      category = Category.find_by(name: category_attributes[:name], owner_id: category_attributes[:owner_id])
      if !category
        category = Category.create(name: category_attributes[:name], owner_id: category_attributes[:owner_id])
      end
      self.categories << category
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :event_users
  has_many :events, through: :event_users
  has_many :categories, through: :events
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable,
        :validatable, :omniauthable, omniauth_providers: %i[facebook]
  accepts_nested_attributes_for :events, :friendships

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.all_except(friends)
    where.not(id: friends)
  end
end

app/controllers/events_controller.rb
class User::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.owner = current_user
    if @event.save
      redirect_to user_event_path(@event)
    else
      render :new
    end
  end

  def update
    if @event.owner == current_user
      if @event.update(event_params)
        redirect_to user_event_path(@event)
      else
        render :edit
      end
    else
      flash[:notice] = "You don't have permission to do this!"
      redirect_to user_events_path
    end
  end

  def edit
  end

  def index
    @events = current_user.events.all
  end

  def show
  end

  def destroy
    @event.destroy
    flash[:notice] = "Event deleted"
    redirect_to user_events_path
  end

  def month
    @events = Event.all
  end

  def week
    @events = Event.all
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:short_description, :date, :time, :additional_info, :user_id, :category_id)
  end
end

app/controllers/user/calendar_controller.rb
class User::CalendarController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dates_events
  helper CalendarHelper
  layout "calendar"

  def month
  end

  def week
  end

  def day
  end

  private

  def set_dates_events
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = current_user.events.group_by(&:date)
  end
end

app/controllers/user/category_controller.rb
class User::CategoryController < ApplicationController
  before_action :authenticate_user!
  helper CategoryHelper
  def index
    @categories = current_user.categories.uniq 
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @category }
    end
  end
end

app/controllers/user/event_controller.rb
class User::EventController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  helper EventHelper

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.owner = current_user
    if @event.save
      current_user.events << @event
      redirect_to user_event_path(@event)
    else
      render :new
    end
  end

  def index
    @events = current_user.events
  end

  def show
  end

  def edit
  end

  def update
    if @event.owner == current_user
    @event.update(event_params)
    if @event.save
        redirect_to user_event_path(@event)
      else
        render :edit
      end
    else
      flash[:notice] = "You don't have permission to do this!"
      redirect_to user_events_path
    end
  end


  def destroy
    @event.delete
    flash[:notice] = "Event deleted"
    redirect_to user_event_index_path
  end

  def unshare
    @user_event = EventUser.find_by(user_id: params[:event][:user_ids])
    @event = Event.find(@user_event.event_id)
    @user_event.delete
    redirect_to user_event_index_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:short_description, :date, :end_time, :start_time, :additional_info, :user_ids, :tag_list, :categories_attributes => [:name, :owner_id])
  end
end

app/controllers/user/friendship_controller.rb
class User::FriendshipController < ApplicationController
  before_action :authenticate_user!
  helper FriendshipHelper
  def new
    @friendship = current_user.friendships.build
  end

  def index

  end

  def create
    if find_friend
      @friendship = current_user.friendships.build(friend_id: friend_params[:user_id])
      if @friendship.save
        flash[:notice] = "Added friend."
        redirect_to root_url
      else
        flash[:notice] = "Unable to add friend."
        redirect_to root_url
      end
    else
      flash[:notice] = "Unable to find friend."
      redirect_to root_url
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by(friend_id: friend_params[:user_id])
    @friendship.delete
    redirect_to root_url
  end

  private

  def find_friend
    user = User.find_by(id: friend_params[:user_id])
    user
  end

  def friend_params
    params.require(:friendship).permit(:user_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  layout 'landing_page'

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  layout 'landing_page'

end

app/helpers/event_helper.rb
module EventHelper
  def upcoming
    if current_user
      events = current_user.events.select {|event| event.date.to_time + event.start_time.seconds_since_midnight.seconds >= Time.zone.now}
      events.sort_by &:date
    end
  end

  def previous
    if current_user
      events = current_user.events.select {|event| event.date.to_time + event.start_time.seconds_since_midnight.seconds < Time.zone.now}
      events.sort_by &:date
    end
  end

  def next_event
    upcoming[0] if current_user && upcoming
  end

  def shared_with
    @event.users.select {|user| user.email != @event.owner.email}
  end

  def shared_with_me?
    shared_with.include?(current_user) ? true : false
  end
end

app/views/user/event/_form.html.erb
<% if @event.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@event.errors.count, "error") %> prohibited this post from being saved:

      <ul class="errors">
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div >
<div class="form-group">
<%= f.label :short_description  %>
<%= f.text_field :short_description, class:"form-control form-control-sm" %>
 </div>
 <div class="form-group ">
<%= f.label :date %>
<%= f.date_field :date,  class:"form-control form-control-sm" %>
 </div>
 <div class="form-row">
<div class="form-group col-md-6">
<%= f.label :start_time %>
<%= f.time_field :start_time ,  class:"form-control form-control-sm" %>
 </div>
<div class="form-group col-md-6">
<%= f.label :end_time %>
<%= f.time_field :end_time,  class:"form-control form-control-sm"  %>
 </div>
</div>
<div class="form-group">
<%= f.label :additional_info %>
<%= f.text_field :additional_info,  class:"form-control form-control-sm"  %>
 </div>
<div class="form-group">
<%= f.label :categories_attributes, 'Category'%>
<%= f.fields_for :categories_attributes, @event.categories.build do |categories_fields| %>
<%= categories_fields.text_field :name,  class:"form-control form-control-sm", id:"cat-tag" %>
<%= categories_fields.hidden_field(:owner_id, value: current_user.id)%>


  <%end%>
   </div>
<div class="form-group">
<%= f.label :user_ids, "Add Your Friends" %>
<%= f.collection_select :user_ids, current_user.friends.all, :id, :email,  class:"form-control" , :include_blank => true%>
</div>
<div class="actions">
<%= f.submit "Submit", class: 'button' %>
</div>

</div>

app/views/user/event/edit.html.erb
<h1>Edit an Event</h1>
<br>

<div class="form-div form">
<%= form_for :event, :url => { :action => "update" }, :method => "patch" do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<%end%>
</div>

app/views/user/event/index.html.erb
<h1>All of Your Events</h1>
<hr>
<h2>Your Events</h2>
<ul id="events-list">
</ul>

app/views/user/event/new.html.erb
<h1 class="text-center">Create a New Event</h1>
<br>
<div class="form-div form">
<%= form_for :event, :url => { :action => "create" }, :html => { :id => "event_form" } do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<%end%>
</div>
<br/>
<hr/>
<div id="eventResult">
  <h2 id="eventName"></h2>
  <div id="event-info"></div>
</div>

app/views/user/event/show.html.erb
<h1>Event</h1>

<ul>
  <li>Short Description: <div id="short_description"><%=@event.short_description %></div></li>
  <li>Starts at: <div id="start_time"><%=@event.start_time.strftime("%l:%M%p") %></div></li>
  <li>Ends at: <div id="end_time"><%=@event.end_time.strftime("%l:%M%p") %></div></li>
  <li>Date: <div id="date"><%=@event.date.strftime("%B %e, %Y")%></div></li>
  <li>Additional Information: <div id="add_info"><%=@event.additional_info%></div></li>
  <li>Created by: <div id="owner"><%=@event.owner.email%></div></li>
</ul>


<% if shared_with_me? %>
<%=button_to "Unshare Myself", user_event_unshare_path(event: {user_ids: current_user.id, id: @event.id}), class: 'button', method: :post, data: { confirm: 'Are you sure?' }%>
<% end%>

<span class="actions">
  <% if @event.owner == current_user%>
  <button class="js-change prev show button" data-id="<%=@event.id%>">Prev Event</button>
  <button class="js-change next show button" data-id="<%=@event.id%>">Next Event</button>
  <%=button_to "Edit", edit_user_event_path(@event), class: "show button", method: :get, form_class: "edit"%>
  <br>
  <%=button_to "Delete", user_event_path, class: "show button", method: :delete, data: {confirm: "Are you sure?"}, form_class: "delete"%>
  <% end %>
</span>