config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  namespace :user do
    resources :event
    resources :friendship
    resources :category, only: [:show, :index, :destroy, :edit, :update]
  end
  authenticated :user do
    root to: 'user/event#new', as: :authenticated_root
  end
  get "/user/calendar/month", to: "user/calendar#month"
  get "/user/calendar/week", to: "user/calendar#week"
  get "/user/calendar/day", to: "user/calendar#day"
  post "/user/event/unshare", to: "user/event#unshare"
  post "/user/friendship/create", to: "user/friendship#create"
  devise_scope :user do
    root to: "user/event#new"
  end
  get "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/calendar.rb
class Calendar < Struct.new(:view, :date, :callback, :user, :type)
  HEADER = %w[Sun Mon Tue Wed Thur Fri Sat]
  DAY_HEADER = %w[Time Events]
  START_DAY = :sunday

  delegate :content_tag, to: :view
  def table
    if type == "day"
      content_tag :table, class: "calendar table day-table" do
        header + hour_rows
      end
    else
      content_tag :table, class: "calendar table table-bordered week" do
        header + rows
      end
    end
  end

  def header
    if type == "day"
        content_tag :tr do
          DAY_HEADER.map { |header| content_tag :th, header, class: "cal-header" }.join.html_safe
        end
    else
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day, class: "cal-header" }.join.html_safe
      end
    end
  end

  def rows
    dates.map do |week|
      content_tag :tr do
        week.map { |day| day_cell(day) }.join.html_safe
      end
    end.join.html_safe
  end

  def day_cell(day)
    content_tag :td, view.capture(day, &callback), class: day_classes(day)
  end

  def day_classes(day)
    classes = []
    if type == "week"
      classes << "week-td"
    end
    classes << make_day_class(day)
    classes << "today" if day == Date.today
    classes.empty? ? nil : classes.join(" ")
  end

  def dates
    if type == "month"
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
    elsif type == "week"
      first = date.beginning_of_week(START_DAY)
      last = date.end_of_week(START_DAY)
    end
    (first..last).to_a.in_groups_of(7)
  end

  def make_day_class(d)
    @events_by_date = user.events.group_by(&:date)
    if @events_by_date[d]
        return "table-warning"
    end
  end
######DAY########
  def hour_rows
    hours.map do |hour|
      content_tag :tr, class: make_class(hour[1]) do
        hour.map {|hr| hour_cell(hr)}.join.html_safe
      end
    end.join.html_safe
  end

  def hour_cell(hour)
    content_tag :td, view.capture(hour, &callback), class: 'day-cal'
  end

  def hours
    from_tm = Time.new(date.year, date.month, date.day, 0, 0, 0)
    to_tm = from_tm + 24.hour
    hr_array = ( from_tm.to_i..to_tm.to_i ).step( 1.hour ).to_a
    make_hours(hr_array)
  end

  def make_hours(array)
    new_array = []
    i = 0
    while i < 24
      new_array.push(array[i])
      new_array.push(i)
      i+=1
    end
    new_array.in_groups_of(2)
  end

  def make_class(hr)
    @events_by_date = user.events.group_by(&:date)
    if @events_by_date[date]
       @events_by_date[date].each do |event|
      if hr >= event.start_time.strftime("%k").to_i && hr <= event.end_time.strftime("%k").to_i
        return "table-warning day-cal"
      end
    end
  end
 end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :event_users
  has_many :events, through: :event_users
  has_many :categories, through: :events
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable,
        :validatable, :omniauthable, omniauth_providers: %i[facebook]
  accepts_nested_attributes_for :events, :friendships

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.all_except(friends)
    where.not(id: friends)
  end
end

app/controllers/user/calendar_controller.rb
class User::CalendarController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dates_events
  helper CalendarHelper
  layout "calendar"

  def month
  end

  def week
  end

  def day
  end

  private

  def set_dates_events
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = current_user.events.group_by(&:date)
  end
end

app/controllers/user/category_controller.rb
class User::CategoryController < ApplicationController
  before_action :authenticate_user!
  helper CategoryHelper
  def index
    @categories = current_user.categories.uniq 
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @category }
    end
  end
end

app/controllers/user/event_controller.rb
class User::EventController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  helper EventHelper

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.owner = current_user
    if @event.save
      current_user.events << @event
      redirect_to user_event_path(@event)
    else
      render :new
    end
  end

  def index
    @events = current_user.events
  end

  def show
  end

  def edit
  end

  def update
    if @event.owner == current_user
    @event.update(event_params)
    if @event.save
        redirect_to user_event_path(@event)
      else
        render :edit
      end
    else
      flash[:notice] = "You don't have permission to do this!"
      redirect_to user_events_path
    end
  end


  def destroy
    @event.delete
    flash[:notice] = "Event deleted"
    redirect_to user_event_index_path
  end

  def unshare
    @user_event = EventUser.find_by(user_id: params[:event][:user_ids])
    @event = Event.find(@user_event.event_id)
    @user_event.delete
    redirect_to user_event_index_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:short_description, :date, :end_time, :start_time, :additional_info, :user_ids, :tag_list, :categories_attributes => [:name, :owner_id])
  end
end

app/controllers/user/friendship_controller.rb
class User::FriendshipController < ApplicationController
  before_action :authenticate_user!
  helper FriendshipHelper
  def new
    @friendship = current_user.friendships.build
  end

  def index

  end

  def create
    if find_friend
      @friendship = current_user.friendships.build(friend_id: friend_params[:user_id])
      if @friendship.save
        flash[:notice] = "Added friend."
        redirect_to root_url
      else
        flash[:notice] = "Unable to add friend."
        redirect_to root_url
      end
    else
      flash[:notice] = "Unable to find friend."
      redirect_to root_url
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by(friend_id: friend_params[:user_id])
    @friendship.delete
    redirect_to root_url
  end

  private

  def find_friend
    user = User.find_by(id: friend_params[:user_id])
    user
  end

  def friend_params
    params.require(:friendship).permit(:user_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  layout 'landing_page'

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  layout 'landing_page'

end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, type, &block)
    Calendar.new(self, date, block, current_user, type).table
  end
end

app/views/user/calendar/day.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to "Previous", user_calendar_day_path(date: @date - 1.day), class: "btn btn-default"%>
      <span style="font-weight:bold"><%= "#{@date.strftime("%b %-d, %Y")}" %></span>
      <%= link_to "Next", user_calendar_day_path(date: @date + 1.day), class: "btn btn-default"%>
    </div>
  </div>
</div>
<div class="row">
    <%= calendar(@date, "day") do |hours| %>
    <%if hours > 24%>
    <%=Time.at(hours).strftime("%l:%M %P")%>
    <%end%>
    <%if @events_by_date[@date]%>
       <%@events_by_date[@date].each do |event| %>
      <% if hours == event.start_time.strftime("%k").to_i  %>
        <%=link_to event.short_description, user_event_path(event)%>: <%=event.start_time.strftime("%l:%M %P")%> — <%=event.end_time.strftime("%l:%M %P")%>
      <% end  %>
     <%end %>
   <%end %>

<%end%>
</div>

app/views/user/calendar/month.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to "Previous", user_calendar_month_path(date: @date - 1.month)%>
      <span style="font-weight:bold"><%= "#{@date.strftime("%B")} #{@date.year}" %></span>
      <%= link_to "Next", user_calendar_month_path(date: @date + 1.month)%>

    </div>
  </div>
</div>
<div class="row">

    <%= calendar(@date, "month") do |date| %>
      <div class="day">
      <%= date.day %>
      </div>
      <% if @events_by_date[date] %>

      <% @events_by_date[date].each do |event| %>
        
        <div class='date event' >
        <%=link_to event.short_description.truncate(15), user_event_path(event)%>
        </div>
      <% end %>

  <% end %>
    <% end %>
</div>

app/views/user/calendar/today.html.erb
<div class="row">
  <div class="text-center">
    <div class="well controls">
      <%= link_to "Previous", user_calendar_week_path(date: @date - 1.day), class: "btn btn-default"%>
      <%= "#{@date.strftime("%b %-d, %Y")}" %>
      <%= link_to "Next", user_calendar_week_path(date: @date + 1.day), class: "btn btn-default"%>

    </div>
  </div>
</div>
<div class="row">
    <%= day_calendar @date do |date| %>
      <!-- <% if @events_by_date[date] %>
    <ul>
      <% @events_by_date[date].each do |event| %>
        <%= link_to event.short_description, user_event_path(event) %>

      <% end %>
    </ul>
  <% end %> -->
    <% end %>
</div>

app/views/user/calendar/week.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to "Previous", user_calendar_week_path(date: @date - 1.week), class: "btn btn-default"%>
      <span style="font-weight:bold"><%= "#{@date.beginning_of_week.strftime("%b %-d, %Y")} - #{@date.end_of_week.strftime("%b %-d, %Y")}" %>
      </span>
      <%= link_to "Next", user_calendar_week_path(date: @date + 1.week), class: "btn btn-default"%>

    </div>
  </div>
</div>
<div class="row">
    <%= calendar(@date, "week") do |date| %>
      <div class="day">
      <%= date.day %>
      </div>
      <% if @events_by_date[date] %>

      <% @events_by_date[date].each do |event| %>
        
        <div class='date event' >
        <%=link_to event.short_description.truncate(15), user_event_path(event)%>
        </div>
      <% end %>

  <% end %>
    <% end %>
</div>