config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  namespace :user do
    resources :event
    resources :friendship
    resources :category, only: [:show, :index, :destroy, :edit, :update]
  end
  authenticated :user do
    root to: 'user/event#new', as: :authenticated_root
  end
  get "/user/calendar/month", to: "user/calendar#month"
  get "/user/calendar/week", to: "user/calendar#week"
  get "/user/calendar/day", to: "user/calendar#day"
  post "/user/event/unshare", to: "user/event#unshare"
  post "/user/friendship/create", to: "user/friendship#create"
  devise_scope :user do
    root to: "user/event#new"
  end
  get "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layout_partials/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-danger" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

app/views/layout_partials/_friends.html.erb
<h5 class="welcome">Hello,
  <%=current_user.email%></h5>
<%if any_friends?%>
  <h3>Your Friends:</h3>
  <ul>
    <% current_user.friendships.each do |friend|%>
      <% user = User.find_by(id: friend.friend_id) %>
      <% if user%>
          <li><%=user.email%>
            <%=button_to "Delete", user_friendship_path(friend.id, friendship: {user_id: user.id}), class: "button", method: :delete, data: { confirm: 'Are you sure?' }%></li>
      <% end %>
      <%end %>
    </ul>
  <%end%>
<h5><%=link_to "Add Friends", new_user_friendship_path%></h5>

app/views/layout_partials/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-faded nav-color">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%=link_to "MyCal", root_url, html_options = {class: "navbar-brand text-white logo"}%>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link text-white" href="/user/calendar/day">Today<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/user/calendar/week">Week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/user/calendar/month">Month<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="/user/event/" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Events
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/user/event/new">New Event</a>
          <a class="dropdown-item" href="/user/event">All Events</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="/user/friendship" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Friends
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/user/friendship/new">New Friend</a>
          <a class="dropdown-item" href="/user/friendship">All Friends</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/user/category">Categories<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link text-white")%>
      </li>
    </ul>
  </div>
</nav>

app/views/layout_partials/_upcoming_events.html.erb
<h5>Next Event:</h5>
<ul>
  <li><%=link_to next_event.short_description, user_event_path(next_event)%>
    -
    <%=next_event.date.strftime("%B %e, %Y")%></li>
</ul>
<br>
<h5>Upcoming Events:</h5>
<ul>
  <% upcoming.each do |event|%>
    <li><%=link_to event.short_description, user_event_path(event)%>
      -
      <%=event.date.strftime("%B %e, %Y")%></li>
  <% end%>
</ul>
<%else%>
<h3>Make a
  <a href="/user/event/new">new event!</a>
</h3>